src/org/jgroups/auth/sasl/SaslClientCallbackHandler.java
Updated fields referenced within the void handle(Callback[]) method as follows:
changed password to client_password
changed name to client_name
=> Correction of partially applied update for PR-185

src/org/jgroups/protocols/pbcast/Merger.java
This PR fixes only the problem reported by Radim
=> BUGFIX JGRP-1876 Each merge, the number of subgroups increments by two

src/org/jgroups/logging/JDKLogImpl.java
Previously, all the logging output gets attributed to JDKLogImpl class,
but with this change, the proper source class name / method name will be
reported.
=> Attribute source class/method names properly

src/org/jgroups/util/Util.java
Jira
https://issues.jboss.org/browse/JGRP-1928
Would this make sense Bela?
=> JGRP-1928 BindException when trying to bind to loopback addresses

src/org/jgroups/auth/sasl/FileObserver.java, src/org/jgroups/auth/sasl/FileWatchTask.java, src/org/jgroups/auth/sasl/SaslClientCallbackHandler.java, src/org/jgroups/auth/sasl/SecurityActions.java, src/org/jgroups/auth/sasl/SimpleAuthorizingCallbackHandler.java, tests/junit-functional/org/jgroups/protocols/SASL_SimpleAuthorizingCallbackTest.java
https://issues.jboss.org/browse/JGRP-1929
=> JGRP-1929 Add a simple properties-based CallbackHandler for the SASL protocol

src/org/jgroups/protocols/MERGE2.java
=> [JGRP-1932] Race condition - MERGE2 with TUNNEL transport is not merging

pom.xml
Hey @belaban !
Please take at some additional changes to the release process. 
I tested it using my own instance with the following command `mvn deploy -Dnexus.server.url=http://10.3.12.5:8081/nexus -DskipTests -Dmaven.test.skip=true`. It worked as expected. 
Thanks
Sebastian
=> Close staging repositories after the release

src/org/jgroups/blocks/MessageDispatcher.java
https://issues.jboss.org/browse/JGRP-1942
=> ISPN-1942 Make MessageDispatcher obtain a log using itself as class instead of using the class name

src/org/jgroups/protocols/SWIFT_PING.java
- Fixes an authentication error in SWIFT_PING, when trying to connect to OpenStack "Kilo".
- OpenStack "Kilo" removes support for XML-formatted authentication responses.
- See https://issues.jboss.org/browse/JGRP-1954 for further details.
=> Fix authentication error in SWIFT_PING.

src/org/jgroups/protocols/TP.java
https://issues.jboss.org/browse/JGRP-1965
=> JGRP-1965 Change default thread pool rejection policy to "abort"

src/org/jgroups/protocols/SASL.java, tests/junit-functional/org/jgroups/protocols/SASLTest.java
https://issues.jboss.org/browse/JGRP-1967
=> JGRP-1967 SASL: correctly handle merge requests

src/org/jgroups/blocks/Cache.java, tests/junit-functional/org/jgroups/blocks/CacheTest.java
=> Fixed Cache.get() to return null when entry is expired

src/org/jgroups/protocols/TP.java
Hi Bela,
This changes was not approved by PM :( so I've been asked to revert it. Here is a PR for it so. 
(ps: my first PR with revert, so I hope I "did it right")
[BZ1275362](https://bugzilla.redhat.com/show_bug.cgi?id=1275362) -  (6.4.z) Change default thread pool rejection policy to "abort"
=> Revert "BZ1275362 - Change default thread pool rejection policy to "a… 

doc/manual/advanced.adoc, src/org/jgroups/protocols/TP.java
As discussed in http://sourceforge.net/p/javagroups/mailman/message/34689441/
=> Improved documentation

src/org/jgroups/protocols/PERF.java
Added missing parameter in a couple of log statements.
=> Fixed log format error in PERF class.

src/org/jgroups/JChannel.java, src/org/jgroups/auth/X509Token.java, src/org/jgroups/blocks/ReplicatedHashMap.java, src/org/jgroups/blocks/cs/NioClient.java, src/org/jgroups/blocks/cs/NioServer.java, src/org/jgroups/blocks/cs/TcpClient.java, src/org/jgroups/blocks/cs/TcpServer.java, src/org/jgroups/blocks/executor/ExecutionService.java, src/org/jgroups/fork/UnknownForkHandler.java, src/org/jgroups/protocols/Executing.java, src/org/jgroups/protocols/TP.java, src/org/jgroups/stack/DefaultRetransmitter.java, src/org/jgroups/util/HashedTimingWheel.java, src/org/jgroups/util/SocketFactory.java, src/org/jgroups/util/TimeScheduler2.java
Hi Bela
I fixed a number of Javadoc warnings from the existing code base, if you want them.
Cheers
Ben
=> Fixed various Javadoc warnings

src/org/jgroups/auth/sasl/SaslUtils.java, src/org/jgroups/conf/ClassConfigurator.java, src/org/jgroups/conf/ProtocolConfiguration.java, src/org/jgroups/conf/XmlConfigurator.java, src/org/jgroups/util/Util.java
This pull request is focused on resolving occurrences of Sonar rule pmd:UseProperClassLoader - Use Proper Class Loader
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseProperClassLoader
M-Ezzat
=> pmd:UseProperClassLoader - Use Proper Class Loader

src/org/jgroups/blocks/PartitionedHashMap.java, src/org/jgroups/blocks/ReplCache.java, src/org/jgroups/blocks/ReplicatedHashMap.java, src/org/jgroups/blocks/mux/NoMuxHandler.java, src/org/jgroups/protocols/DELAY.java, src/org/jgroups/protocols/ENCRYPT.java, src/org/jgroups/protocols/FRAG.java, src/org/jgroups/protocols/PRIO.java, src/org/jgroups/protocols/S3_PING.java, src/org/jgroups/protocols/SEQUENCER2.java, src/org/jgroups/protocols/SWIFT_PING.java, src/org/jgroups/protocols/tom/DeliveryManagerImpl.java, src/org/jgroups/protocols/tom/DeliveryThread.java, src/org/jgroups/protocols/tom/SenderManager.java, src/org/jgroups/protocols/tom/StatsCollector.java
This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
M-Ezzat
=> pmd:ImmutableField - Immutable Field

src/org/jgroups/JChannel.java, src/org/jgroups/auth/sasl/SimpleAuthorizingCallbackHandler.java, src/org/jgroups/blocks/GroupRequest.java, src/org/jgroups/blocks/MessageDispatcher.java, src/org/jgroups/blocks/cs/NioConnection.java, src/org/jgroups/demos/wb/Whiteboard.java, src/org/jgroups/protocols/BARRIER.java, src/org/jgroups/protocols/COUNTER.java, src/org/jgroups/protocols/FD_SOCK.java, src/org/jgroups/protocols/FlowControl.java, src/org/jgroups/protocols/JDBC_PING.java, src/org/jgroups/protocols/Locking.java, src/org/jgroups/protocols/RATE_LIMITER.java, src/org/jgroups/protocols/SEQUENCER2.java, src/org/jgroups/protocols/STOMP.java, src/org/jgroups/protocols/TCPPING.java, src/org/jgroups/protocols/TP.java, src/org/jgroups/protocols/UDP.java, src/org/jgroups/protocols/pbcast/NAKACK2.java, src/org/jgroups/protocols/pbcast/STATE.java, src/org/jgroups/protocols/relay/Relayer.java, src/org/jgroups/stack/Configurator.java, src/org/jgroups/util/ProcessingQueue.java, src/org/jgroups/util/Util.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1066 - Collapsible "if" statements should be merged
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1066
M-Ezzat
=> squid:S1066 - Collapsible if statements should be merged

src/org/jgroups/JChannel.java, src/org/jgroups/client/StompConnection.java, src/org/jgroups/demos/KeyStoreGenerator.java, src/org/jgroups/protocols/ENCRYPT.java, src/org/jgroups/protocols/STOMP.java, src/org/jgroups/stack/ProtocolStack.java, src/org/jgroups/util/Util.java
This pull request is focused on resolving occurrences of Sonar rule pmd:UseIndexOfChar - Use Index Of Char
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:UseIndexOfChar
M-Ezzat
=> pmd:UseIndexOfChar - Use Index Of Char

src/org/jgroups/protocols/TP.java
Maybe all this is intentional and this makes no sense, but maybe:
DONT_BUNDLE+OOB 
* messages are not removed from batch when execution fails
* rejections are not counted to num_rejected_msgs
* spurious logging per message overfills the log
* treat failures other than RejectedExecutionException as errors (as batch processing does)
=> JGRP-2015 Fixes around new DONT_BUNDLE+OOB processing:

src/org/jgroups/auth/sasl/SaslUtils.java, src/org/jgroups/conf/ClassConfigurator.java, src/org/jgroups/conf/ProtocolConfiguration.java, src/org/jgroups/conf/XmlConfigurator.java, src/org/jgroups/util/Util.java
https://issues.jboss.org/browse/JGRP-2035
We'll need a 3.6.9.Final release containing this fix ASAP.
=> [3.6] JGRP-2035 Revert "pmd:UseProperClassLoader - Use Proper Class Loader"

src/org/jgroups/auth/sasl/SaslUtils.java, src/org/jgroups/conf/ClassConfigurator.java, src/org/jgroups/conf/ProtocolConfiguration.java, src/org/jgroups/conf/XmlConfigurator.java, src/org/jgroups/util/Util.java
https://issues.jboss.org/browse/JGRP-2035
=> [master] JGRP-2035 Revert "pmd:UseProperClassLoader - Use Proper Class Loader"

src/org/jgroups/protocols/S3_PING.java
protocol
I love a one-character fix!
=> JGRP-2051 S3_PING.generatePreSignedUrl() has to use https for the

src/org/jgroups/util/XMLSchemaGenerator.java
https://issues.jboss.org/browse/JGRP-2046
With this also backported to 3.6.x its pretty cool, here is a report I can now make of configuration differences between 3.6.8.Final and 4.0.0-SNAPSHOT:
https://gist.github.com/rhusar/67abf87afdd556700a424b35772ad67a
=> JGRP-2046 Order of XSD protocol elements and protocol attributes is arbitrary

doc/manual/en/modules/installation.xml, src/org/jgroups/Global.java, src/org/jgroups/logging/CustomLogFactory.java, src/org/jgroups/logging/LogFactory.java
Backport JGRP-2060 to 3.3 branch.
https://issues.jboss.org/browse/JGRP-2060
https://bugzilla.redhat.com/show_bug.cgi?id=1330729
=> 3.3 JGRP-2060

src/org/jgroups/util/Rsp.java
https://issues.jboss.org/browse/JGRP-2094
=> JGRP-2094 Add convenience method Rsp.readIn

src/org/jgroups/protocols/COUNTER.java
=> #317 to master

src/org/jgroups/protocols/ASYM_ENCRYPT.java
Jira: https://issues.jboss.org/browse/JGRP-2121
=> [JGRP-2121] Logs ASYM_ENCRYPT message "key server is currently not set" with debug level

src/org/jgroups/protocols/FD_HOST.java
JIRA: https://issues.jboss.org/browse/JGRP-2144
=> [JGRP-2144] Use error log method with Throwable

src/org/jgroups/protocols/dns/DefaultDNSResolver.java, tests/junit-functional/org/jgroups/protocols/dns/DNSDiscoveryTester.java, tests/junit-functional/org/jgroups/protocols/dns/DefaultDNSResolverTest.java, tests/junit-functional/org/jgroups/protocols/dns/MockDirContext.java
https://issues.jboss.org/browse/JGRP-1388
Additional resolver tests for DNS_PING.
=> JGRP-1388 Additional tests fort DNS_PING

doc/manual/protocols.adoc, pom.xml
https://issues.jboss.org/browse/JGRP-1388
Additional documentation for `DNS_PING`.
Hey @belaban! 
This is the last PR for `DNS_PING`. I created a PR (and not pushed directly) because I wanted you to take a look if I didn't miss any spot where we need additional documentation.
Cheers!
=> Jgrp 1388/dns ping documentation

src/org/jgroups/protocols/UNICAST2.java
https://issues.jboss.org/browse/JGRP-2198 
@belaban could you please review? Esp. I am not sure if a similar change is required in UNICAST3.
=> [JGRP-2198] Reduce log level for RequestCorrelator "channel is not

src/org/jgroups/protocols/UNICAST3.java
https://issues.jboss.org/browse/JGRP-2198
https://github.com/belaban/JGroups/pull/351 ported to UNICAST3. 
@belaban could you please review? Once you approve here, I can send a PR against master too.
=> [JGRP-2198] UNICAST3: Reduce log level for RequestCorrelator "channel is

src/org/jgroups/protocols/UNICAST2.java, src/org/jgroups/protocols/UNICAST3.java
https://issues.jboss.org/browse/JGRP-1958 https://issues.jboss.org/browse/JGRP-2198
Backport of https://github.com/belaban/JGroups/commit/03d7c93145f6a9314c2380f5ad66bdc8ec4209f0 for JGRP-1958 and
https://github.com/belaban/JGroups/pull/351 https://github.com/belaban/JGroups/pull/352
=> Backport JGRP-1958 and JGRP-2198 to 3.5

src/org/jgroups/protocols/UNICAST2.java, src/org/jgroups/protocols/UNICAST3.java
https://issues.jboss.org/browse/JGRP-1958 https://issues.jboss.org/browse/JGRP-2198
Backport of 03d7c93 for JGRP-1958 and
#351 #352
=> Backport JGRP-1958 and JGRP-2198 to 3.4

src/org/jgroups/protocols/UNICAST2.java, src/org/jgroups/protocols/UNICAST3.java
https://issues.jboss.org/browse/JGRP-1958 https://issues.jboss.org/browse/JGRP-2198
Backport of 03d7c93 for JGRP-1958 and
#351 #352
=> Backport JGRP-1958 and JGRP-2198 to 3.3

src/org/jgroups/protocols/UNICAST2.java
https://issues.jboss.org/browse/JGRP-2198
EAP 6.4 https://bugzilla.redhat.com/show_bug.cgi?id=1463387
back port of #351
=> Backport JGRP-2198 to 3.2

src/org/jgroups/protocols/tom/DeliveryManagerImpl.java, src/org/jgroups/protocols/tom/TOA.java, tests/junit/org/jgroups/protocols/TOA_UnitTest.java
https://issues.jboss.org/browse/JGRP-2217
Ignore messages from non-members now.
Also, added a unit test for TOA protocol (to be extended in the future :))
Feel free to comment
=> JGRP-2217 TOA doesn't ignore DATA_MESSAGE from non-members

src/org/jgroups/stack/Protocol.java
https://issues.jboss.org/browse/JGRP-2226
=> JGRP-2226 Add Protocol.setProperties(Map<String, String>) method to allow programmatic configuration of arbitrary properties

src/org/jgroups/protocols/dns/DNSResolver.java, src/org/jgroups/protocols/dns/DNS_PING.java, src/org/jgroups/protocols/dns/DefaultDNSResolver.java, tests/junit-functional/org/jgroups/protocols/dns/DNSDiscoveryTester.java, tests/junit-functional/org/jgroups/protocols/dns/DNS_PINGTest.java
https://issues.jboss.org/browse/JGRP-2223
=> JGRP-2223 Make DNS_PING more user-friendly

src/org/jgroups/protocols/pbcast/GMS.java
Jira
https://issues.jboss.org/browse/JGRP-2231
=> JGRP-2231 Intermittent NPE in JGroups GMS#up on shutdown

src/org/jgroups/auth/MD5Token.java
I know the sample AuthToken implementations are meant to be sample code, and not used in production, but I'll have a go at fixing some bugs that I think I see.
=> Some fixes to auth.MD5Token

src/org/jgroups/AnycastAddress.java, src/org/jgroups/protocols/tom/DeliveryManagerImpl.java, src/org/jgroups/protocols/tom/TOA.java, src/org/jgroups/protocols/tom/ToaHeader.java, tests/junit/org/jgroups/protocols/TOA_UnitTest.java
https://issues.jboss.org/browse/JGRP-2233
Comments/Suggestions are welcome.
=> JGRP-2233 TOA is ignoring too many messages

src/org/jgroups/protocols/dns/DNS_PING.java, tests/junit-functional/org/jgroups/protocols/dns/DNS_PINGTest.java
https://issues.jboss.org/browse/JGRP-2254
=> Jgrp 2254/default dns address

doc/manual/protocols.adoc
Hey!
I extended a few bits on `DNS_PING` docs. Please have a look and tell me what do you think about it.
Thanks,
Seb
//cc @pferraro @rhusar @luck3y
=> Extended DNS_PING documentation

src/org/jgroups/protocols/SASL.java
Looks like a copy paste error missed in review.
If anybody thinks we need to keep binary compatibility here let me know.
=> Fix SASL#getServerName

src/org/jgroups/annotations/XmlElement.java
=> Fix dangling @XmlElement JavaDoc

src/org/jgroups/protocols/VERIFY_SUSPECT.java
https://issues.jboss.org/browse/JGRP-2286
=> JGRP-2286 VERIFY_SUSPECT can return false positives if member is killed and immediately restarted

src/org/jgroups/protocols/VERIFY_SUSPECT.java
=> Revert "JGRP-2286 VERIFY_SUSPECT can return false positives if member is killed and immediately restarted"

tests/junit-functional/org/jgroups/tests/ConcurrentLeaversTest.java
https://issues.jboss.org/browse/JGRP-2293
=> Reproducer for JGRP-2293

tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_LeaveTest.java
See https://issues.jboss.org/browse/JGRP-2297
=> Reproducer for JGRP-2297

src/org/jgroups/protocols/dns/AddressedDNSResolver.java, src/org/jgroups/protocols/dns/DNS_PING.java, src/org/jgroups/protocols/dns/DefaultDNSResolver.java
https://issues.jboss.org/browse/JGRP-2295
https://issues.jboss.org/browse/JGRP-2292
Signed-off-by: rcernich <rcernich@redhat.com>
=> JGRP-2295 use InetAddress.getAllByName() for DNS_PING A record lookups

src/org/jgroups/logging/Slf4jLogImpl.java
Fixes https://issues.jboss.org/browse/JGRP-2307
=> JGRP-2307 Fix bug in Slf4jLogImpl

src/org/jgroups/protocols/Encrypt.java
https://issues.jboss.org/browse/JGRP-2302
=> JGRP-2302 Default ASYM_ENCRYPT asym_keylength is considered breakable

src/org/jgroups/protocols/ASYM_ENCRYPT.java, src/org/jgroups/protocols/Encrypt.java
https://issues.jboss.org/browse/JGRP-2279
=> JGRP-2279 Fix BadPaddingExceptions if cipher contains state from previous failure.

src/org/jgroups/protocols/FD_ALL.java, src/org/jgroups/protocols/FD_ALL2.java, src/org/jgroups/protocols/VERIFY_SUSPECT.java
https://issues.jboss.org/browse/JGRP-2321
=> JGRP-2321 Failure detection protocols should log all events

src/org/jgroups/util/XMLSchemaGenerator.java
https://issues.jboss.org/browse/JGRP-2322
=> JGRP-2322 Make protocol attributes extensible in the schema

src/org/jgroups/blocks/executor/ExecutionCompletionService.java, src/org/jgroups/blocks/executor/Executions.java, src/org/jgroups/nio/Buffers.java, src/org/jgroups/stack/Protocol.java
I've just come across a couple of typos in the javadoc.
=> A few typos fixed in the javadoc.

build.xml, conf/fork-stacks.xsd, conf/relay.xsd, pom.xml, src/org/jgroups/util/XMLSchemaGenerator.java
https://issues.jboss.org/browse/JGRP-2323
=> JGRP-2323 Use correct namespace for element types

src/org/jgroups/protocols/pbcast/GMS.java
https://issues.jboss.org/browse/JGRP-2333
=> JGRP-2333 pbcast.GMS#getView returns ViewId as opposed to the View

src/org/jgroups/blocks/cs/NioConnection.java, src/org/jgroups/blocks/cs/NioServer.java, src/org/jgroups/util/SocketFactory.java
https://issues.jboss.org/browse/JGRP-2339
https://issues.jboss.org/browse/JGRP-2340
=> JGRP-2339, JGRP-2340 Add missing SocketFactory methods for NIO channels

src/org/jgroups/blocks/ReplicatedHashMap.java, tests/junit/org/jgroups/tests/ReplicatedHashMapTest.java
Writes are now replicated across the cluster.
Currently SynchronizedReplicationMap remains broken. Maybe add an annotion maybe fix it?...
Development was a bit weird. the maven pom doesn't seem to work, a lot of tests fail under linux, 
ReplicatedHashMapTest doesn't work under Macos using udp, but it does under linux or using tcp. 
Are these things normal?
=> ReplicatedHashMapViews are replicated

src/org/jgroups/fork/ForkProtocolStack.java, src/org/jgroups/protocols/FORK.java, tests/junit-functional/org/jgroups/tests/ForkChannelTest.java, tests/junit/org/jgroups/protocols/FORK_UnitTest.java
https://issues.jboss.org/browse/JGRP-2354
=> JGRP-2354 ForkChannel does not receive SITE_UNREACHABLE events

src/org/jgroups/protocols/relay/Relayer.java
https://issues.jboss.org/browse/JGRP-2359
See JIRA for details. 
I decided to do a copy to perform the changes from the view change. However, I'm open to suggestions.
Also, the Relay2Test is failing (for me) in master and I was unable to test if this breaks anything :)
=> JGRP-2359 Route list can be empty

src/org/jgroups/protocols/SSL_KEY_EXCHANGE.java
Jiras
https://issues.jboss.org/browse/JGRP-2370
https://issues.jboss.org/browse/JGRP-2371
Blocks
https://issues.jboss.org/browse/WFLY-12164
=> JGRP-2370 JGRP-2371 SSL_KEY_EXCHANGE Elytron integrationability fixes

src/org/jgroups/protocols/relay/config/RelayConfig.java
JGRP-2379 Support custom variables in the attribute value for relay.RELAY2#config
=> JGRP-2379 Support custom variables in the attribute value for relay.RELAY2#config

conf/asym-encrypt.xml, conf/asym-ssl.xml, conf/encrypt.xml, conf/sym-encrypt.xml, doc/manual/protocols.adoc
I updated the examples in the manual and in the conf folder to use AES/CBC/PKCS5Padding.
=> Switching to AES/CBC/PKCS5Padding in manual and conf examples.

src/org/jgroups/jmx/JmxConfigurator.java, tests/junit-functional/org/jgroups/tests/JmxTest.java
https://issues.jboss.org/browse/JGRP-2394
=> JGRP-2394 Provide ObjectName prefix also for unregistrations

src/org/jgroups/protocols/TP.java
https://issues.redhat.com/browse/JGRP-2428
=> JGRP-2428 Add message size to TP::down trace log

src/org/jgroups/JChannel.java
https://issues.redhat.com/browse/JGRP-2437
=> JGRP-2437 Log local_addr and name in JChannel

pom.xml
Fixes the certificate error when following the link
=> Update Jira link in pom.xml

src/org/jgroups/protocols/FD.java
The FD Monitor was split into a heartbeat sender task and a timeout check task, similar to FD_ALL and FD_ALL2. This prevents the timeout check in the FD protocol from being block by the transport.
Ticket: https://issues.redhat.com/browse/JGRP-2486.
=> JGRP-2486 FD Monitor gets stuck on TransferQueueBundler

src/org/jgroups/protocols/Discovery.java, src/org/jgroups/protocols/JDBC_PING.java, tests/junit/org/jgroups/tests/SequencerOrderTest.java
JIRA: https://issues.redhat.com/browse/JGRP-2199
Port of https://github.com/belaban/JGroups/commit/9b5aeb5ea28d99fb104dafe2e98e6ee9146b5eb5 https://github.com/belaban/JGroups/commit/c9854980bc7c693376248cc84802f9c39d567095 for 4.1 branch
=> [JGRP-2199] JDBC_PING cluster doesn't handle shutdown members

src/org/jgroups/protocols/relay/RELAY2.java, tests/junit-functional/org/jgroups/tests/Relay2RpcDispatcherTest.java
https://issues.redhat.com/browse/JGRP-2545
=> [4.x] JGRP-2545 Expose online site names

src/org/jgroups/protocols/relay/RELAY2.java, tests/junit-functional/org/jgroups/tests/Relay2RpcDispatcherTest.java
https://issues.redhat.com/browse/JGRP-2545
=> JGRP-2545 Expose online site names

src/org/jgroups/blocks/cs/NioBaseServer.java
Fixes https://issues.redhat.com/browse/JGRP-2531
=> Changed the order of checking for connectable and readable keys 

ivy.xml, src/org/jgroups/auth/sasl/SimpleAuthorizingCallbackHandler.java, tests/junit-functional/org/jgroups/protocols/SASLTest.java
https://issuers.redhat.com/browse/JGRP-2487
=> [4.x] JGRP-2487 Fix TLSTest and SASL tests

src/org/jgroups/stack/GossipRouter.java
Added new options for '-dump_msgs'
https://issues.redhat.com/browse/JGRP-2568
I decided to change the `-dump_msgs` but I think a cleaner solution would be to drop the option and add proper logging categories :) 
maybe another day...
=> [4.x] JGRP-2568 Log membership changes in GossipRouter

src/org/jgroups/stack/GossipRouter.java
Added new options for '-dump_msgs'
https://issues.redhat.com/browse/JGRP-2568
=> [5.x] JGRP-2568 Log membership changes in GossipRouter

tests/perf/org/jgroups/tests/perf/MPerf.java
Adds the ability to specify an output file path for use in automated testing.
=> Add option to write MPerf results to file

.github/workflows/ci.yml, .travis.yml
master: https://github.com/belaban/JGroups/pull/569
=> [4.x] Introduce continuous integration testing using GitHub Actions

src/org/jgroups/blocks/cs/NioBaseServer.java
Thanks @belaban for merging my previous PR https://github.com/belaban/JGroups/pull/571
This is the backport of the same change to the 4.x branch.
=> JGRP-2531 Handle case where finishConnect() returns false even though isConnectable() returned true.

src/org/jgroups/protocols/relay/RELAY2.java
https://issues.redhat.com/browse/JGRP-2589
=> JGRP-2589 Remove Flag.INTERNAL from SITE_UNREACHABLE message

conf/fork-stacks-4.2.xsd, conf/fork-stacks.xml, conf/relay-4.2.xsd, conf/relay1.xml, conf/relay2.xml, conf/rules-4.2.xsd, conf/rules.xml, conf/tcp-nio.xml, conf/tcp.xml, conf/tcpgossip.xml, doc/manual/advanced.adoc, doc/manual/protocols.adoc, src/org/jgroups/annotations/XmlInclude.java, src/org/jgroups/fork/ForkConfig.java
https://issues.redhat.com/browse/JGRP-2590
=> [4.x] JGRP-2590 Version XSDs

src/org/jgroups/blocks/atomic/AsyncCounter.java, src/org/jgroups/blocks/atomic/Counter.java, src/org/jgroups/blocks/atomic/CounterService.java, src/org/jgroups/blocks/atomic/SyncCounter.java, src/org/jgroups/protocols/COUNTER.java, src/org/jgroups/util/CompletableFutures.java
https://issues.redhat.com/browse/JGRP-2614
=> JGRP-2614 Non-blocking API for counters

src/org/jgroups/protocols/VERIFY_SUSPECT2.java
https://issues.redhat.com/browse/JGRP-2618
=> ThreadFactory name for VERIFY_SUSPECT2 must match the class name

tests/other/org/jgroups/tests/ParseMessages.java, tests/other/org/jgroups/tests/ParseMessagesFields.java
Output example:
```
15:23:07,782 9090 46655 1: [dlovison-mac-21990 to <all>, 50 bytes, flags=OOB|DONT_BUNDLE], hdrs: PING: [GET_MBRS_REQ cluster=qa-cluster initial_discovery=true], TP: [cluster=qa-cluster] 
15:23:08,437 9090 46655 2: [dlovison-mac-21990 to <all>, 50 bytes, flags=OOB|DONT_BUNDLE], hdrs: PING: [GET_MBRS_REQ cluster=qa-cluster initial_discovery=true], TP: [cluster=qa-cluster] 
15:23:09,099 9090 46655 3: [dlovison-mac-21990 to <all>, 50 bytes, flags=OOB|DONT_BUNDLE], hdrs: PING: [GET_MBRS_REQ cluster=qa-cluster initial_discovery=true], TP: [cluster=qa-cluster] 
```
=> Parse Tshark fields

build.properties.template, doc/design/NIO2.txt, doc/manual/advanced.adoc, doc/manual/installation.adoc, doc/manual/protocols.adoc, doc/tutorial/installation.adoc, src/org/jgroups/Global.java, src/org/jgroups/demos/ProgrammaticChat.java, src/org/jgroups/protocols/UDP.java, src/org/jgroups/stack/DiagnosticsHandler.java, src/org/jgroups/util/ResourceManager.java, tests/junit-functional/org/jgroups/tests/IpAddressTest.java, tests/junit-functional/org/jgroups/tests/Relay2Test.java, tests/other/org/jgroups/tests/McastDiscovery.java, tests/other/org/jgroups/tests/McastReceiverTest.java, tests/other/org/jgroups/tests/McastSenderTest.java, tests/other/org/jgroups/tests/ModClusterAdvertizeListener.java, tests/other/org/jgroups/tests/MulticastTest2.java, tests/other/org/jgroups/tests/mcast.java, tests/perf/org/jgroups/tests/perf/ProgrammaticUPerf.java, tests/perf/org/jgroups/tests/perf/ProgrammaticUPerf2.java, tests/perf/org/jgroups/tests/perf/UdpPerf.java
https://issues.redhat.com/browse/JGRP-2627
=> JGRP-2627 Change multicast address to private network

src/org/jgroups/blocks/atomic/AsyncCounter.java, src/org/jgroups/blocks/atomic/CounterFunction.java, src/org/jgroups/blocks/atomic/CounterView.java, src/org/jgroups/blocks/atomic/SyncCounter.java, src/org/jgroups/protocols/COUNTER.java, src/org/jgroups/util/LongSizeStreamable.java, tests/junit-functional/org/jgroups/blocks/CounterTest.java
2 usage examples in `CounterTest`.
https://issues.redhat.com/browse/JGRP-2630
=> JGRP-2630 Create update function for counters

src/org/jgroups/blocks/cs/TcpConnection.java
https://issues.redhat.com/browse/JGRP-2637
=> JGRP-2637 Quiet SSLHandshakeExceptions caused by closed sockets

src/org/jgroups/protocols/SSL_KEY_EXCHANGE.java, src/org/jgroups/stack/GossipRouter.java, src/org/jgroups/util/SslContextFactory.java
https://issues.redhat.com/browse/JGRP-2638
=> JGRP-2638 Improve GossipRouter TLS support

src/org/jgroups/protocols/FD_SOCK2.java
https://issues.redhat.com/browse/JGRP-2648
=> JGRP-2648 FD_SOCK2 ignores any configured socket and thread factories

src/org/jgroups/blocks/cs/NioConnection.java, src/org/jgroups/protocols/BasicTCP.java, src/org/jgroups/protocols/FD_SOCK2.java
https://issues.redhat.com/browse/JGRP-2649
=> JGRP-2649 Add configuration property to FD_SOCK2 to configure SO_LINGER of client sockets

src/org/jgroups/util/CompletableFutures.java
https://issues.redhat.com/browse/JGRP-2658
=> JGRP-2658 Move CompletableFutures from jgroups-raft to JGroups

src/org/jgroups/protocols/COUNTER.java
https://issues.redhat.com/browse/JGRP-2662
=> JGRP-2662 COUNTER: create num_backups setter

src/org/jgroups/blocks/atomic/AsyncCounter.java, src/org/jgroups/blocks/atomic/BaseCounter.java, src/org/jgroups/blocks/atomic/SyncCounter.java
https://issues.redhat.com/browse/JGRP-2663
=> JGRP-2663 Merge counter's API from jgroups-raft into jgroups

.gitignore, src/org/jgroups/protocols/SSL_KEY_EXCHANGE.java, src/org/jgroups/util/SslContextFactory.java, tests/junit-functional/org/jgroups/protocols/SSL_KEY_EXCHANGE_ReloadTest.java
https://issues.redhat.com/browse/JGRP-2667
=> JGRP-2667: SSL_KEY_EXCHANGE: Support certificate reload and explicit truststore

src/org/jgroups/util/Util.java
=> Fix android missing Matcher.appendReplacement(StringBuffer, String);

src/org/jgroups/util/ByteArrayDataInputStream.java
Mirror of https://github.com/belaban/JGroups/blob/master/src/org/jgroups/util/ByteArrayDataOutputStream.java#L31-L33
=> Expose byte[] for ByteArrayDataInputStream

src/org/jgroups/protocols/dns/AddressedDNSResolver.java, src/org/jgroups/protocols/dns/DNS_PING.java, src/org/jgroups/protocols/dns/DefaultDNSResolver.java
https://issues.redhat.com/browse/JGRP-2691
=> JGRP-2691 Expose public methods to DNS_PING for configuring DNSResolver

pom.xml
[ISPN-15109](https://issues.redhat.com/browse/ISPN-15109) for more context.
=> Mark byteman dependency as Optional

src/org/jgroups/protocols/JDBC_PING.java
https://issues.redhat.com/browse/JGRP-2756
=> JGRP-2756 Look for JDBC drivers in multiple classloaders

src/org/jgroups/protocols/JDBC_PING.java
https://issues.redhat.com/browse/JGRP-2756
=> [4.x] JGRP-2756 Look for JDBC drivers in multiple classloaders

conf/relay.xsd, src/org/jgroups/annotations/XmlInclude.java, src/org/jgroups/protocols/FORK.java, src/org/jgroups/protocols/relay/RELAY.java, src/org/jgroups/util/XMLSchemaGenerator.java
https://issues.redhat.com/browse/JGRP-2764
@belaban we might want to change all the files in `/conf/` to use the jgroups xsd instead of the relay/fork xsds as well as amending the documentation
=> JGRP-2764 Support XML schema embedding

src/org/jgroups/stack/GossipRouter.java
https://issues.redhat.com/browse/JGRP-2805
=> [5.3.x] JGRP-2805 GossipRouter NPE on startup

src/org/jgroups/protocols/FORK.java, src/org/jgroups/protocols/relay/RELAY.java
Fixes https://issues.redhat.com/browse/JGRP-2823.
=> [JGRP-2823] Fix XML Schema generation

src/org/jgroups/BytesMessage.java
This change adds a helper to get the bytes from BytesMessage. Borrowed from ByteArray.
=> BytesMessage helper

src/org/jgroups/protocols/ReliableMulticast.java, src/org/jgroups/protocols/ReliableUnicast.java
This change makes it so warnings are logged when sends are dropped by ReliableMulticast/Unicast because send buffers are full.
=> Log dropped sends in Make ReliableMulticast/Unicast

src/org/jgroups/protocols/JDBC_PING2.java
This should resolve pinning when using virtual threads and JGroups.
This applies https://foojay.io/today/how-to-diagnose-and-mitigate-pinning-in-javas-virtual-thread-execution/ and applies the remedies suggested in https://foojay.io/today/lets-replace-the-synchronized-keyword/
=> JGRP-2861 Avoiding JDBC_PING2 synchronized as it would pin the threads when using virtual threads

src/org/jgroups/protocols/ReliableMulticast.java, src/org/jgroups/protocols/ReliableUnicast.java
Reverts #876 since sends can no longer be dropped due to 0c16aa4
=> Remove log of dropped sends in Make ReliableMulticast/Unicast
