- src/org/jgroups/fork/ForkProtocolStack.java
For JGRP-1905.  Better to drop the message (i.e. like we already to for message batches) than throw an NPE.
> Fix NPE if message arrives for unregistered fork.

- src/org/jgroups/fork/ForkChannel.java
- src/org/jgroups/fork/ForkProtocolStack.java
- src/org/jgroups/fork/UnknownForkHandler.java
- src/org/jgroups/protocols/FORK.java
https://issues.jboss.org/browse/JGRP-1905
Exposes a mechanism to allow the creator of FORK to define how unknown forks should be handled.
> JGRP-1905 FORK: RPCs might block if fork channel or fork stack is not available

- src/org/jgroups/protocols/JDBC_PING.java
In managed containers (Spring ApplicationContext, J2EE ServletContext) the JConnector will be shut down gracefully when the context is closed.
Shutdown hooks registered with the JVM will result in ugly errors when the JVM exists (classes needed to execute it have been unloaded). They also cause memory leaks since they can't be unloaded by the Tomcat (or similar) server.
This adds a configuration option register_shutdown_hook to conditionally disable the creation of a shutdown hook. The default is true to maintain the current behavior.
> Add option to stop JDBC_PING from registering a shutdown hook

- tests/junit/org/jgroups/tests/SequencerMergeTest.java
The intention of this loop is that if at first the four members don't have the right details, then wait a bit and try again.  Only it misses the "try again" part.
> Fix flakey unit test

- build.xml
-  make sure that the required artifacts are built first, by depending on the "jar" task
-  ivy:resolve all dependencies
I'm no ivy expert but google told me to do the second thing and it worked.  Prior to that I was hitting 
impossible to publish artifacts for org.jgroups#jgroups;3.6.3.Final: java.lang.IllegalStateException: Ivy file not found in cache for org.jgroups#jgroups;3.6.3.Final!
To reproduce this problem I think that you may need to `rm -fr ~/.ivy2/cache` before trying `ant publish-local`
> Fix 'ant publish-local'

- project.properties
Upon merge and reindex by jgroups, it fixes the description here http://www.jboss.org/projects/ and searching for jgroups and clicking the project logo.
> Fix project description on jboss.org project matrix

- pom.xml
Hey @belaban !
Recently I've been looking at different ways to release without staging repo. Luckily, this problem has been solved by Hawkular project [1]. 
Maybe it's worth trying this approach before customizing repositories at JBoss Nexus?
Thanks
Sebastian
[1] https://issues.jboss.org/browse/HAWKULAR-199 and implementation [2][3]
[2] https://github.com/hawkular/hawkular-build-tools/commit/b48133af85de156f3f7e14a68cab48704d81cb16
[3] https://github.com/hawkular/hawkular-build-tools/commit/bfe907f31ed4c4afbe9a6745303d48feda2a60f9
> Release JGroups avoiding stagig repo

- conf/jg-protocol-ids.xml
Hi Bela,
The clean approach is that extra projects should actually use org.jgroups.PROJECT package name, so that a repository jgroups-PROJECT contains the relevant classes/files. So e.g. in repo jgroups-azure shoud reside all classes in org.jgroups.azure package.
Cheers,
Rado
> JGRP-1909 Use org.jgroups.azure for the protocol ID instead

- src/org/jgroups/auth/X509Token.java
This behavior is consistent with how the ENCRYPT protocol looks for a keystore.
> Make X509Token look in the classpath for the keystore.

- src/org/jgroups/protocols/MERGE3.java
Unless I am missing something, the property annotation should move to the field instead of being twice on the get/set methods.
Noticed this when looking at the schema which was generated invalid because the properties were occuring twice, e.g.:
```xsd
<xs:element name="MERGE3">
<xs:complexType>
<xs:attribute name="min_interval" type="xs:string"/>
<xs:attribute name="min_interval" type="xs:string">
<xs:annotation>
<xs:documentation>Minimum time in ms before sending an info message</xs:documentation>
</xs:annotation>
</xs:attribute>
...
```
This makes the schema valid again. T. Hanks.
> Fix MERGE3 @Property for min_interval and max_interval

- src/org/jgroups/fork/ForkProtocolStack.java
Reasoning: this isn't indicative of a problem - just an asymmetric cluster.
> Lower log level when messages are received for an unknown fork.

- src/org/jgroups/protocols/TP.java
Switch error message to trace, as we discussed over IRC. However, let me know if you think we should handle this in a better fashion.
> BZ1247250: Jgroups: null: logical address cache didn't contain all physical address

- src/org/jgroups/Global.java
- src/org/jgroups/blocks/RequestCorrelator.java
- tests/junit/org/jgroups/blocks/RpcDispatcherUnicastMethodExceptionTest.java
Wasn't sure what branch to push this to, I didn't see one with 3.6.7-SNAPSHOT.  So i'll let you guys figure that out.  
I encountered a problem with wrapped exceptions between JDK 6 (Android-18) & JDK 7.   ```RequestCorrelator``` wraps *thrown* exceptions with ```InvocationTargetException```.. which has had the same ```serialVersionUID``` since Java 1.1.  But on JDK 1.7 ```InvocationTargetException extends ReflectiveOperationException``` *(which has a different serialVersionUID)*. Exceptions thrown are serialized and I get an exception because the serialVersionUID doesn't match.
```
java.io.InvalidClassException: java.lang.ReflectiveOperationException; Incompatible class (SUID): java.lang.ReflectiveOperationException: static final long serialVersionUID =123456789L; but expected …
```
> Added option to not wrap exceptions with InvocationTargetException

- tests/junit/org/jgroups/blocks/RpcDispatcherUnicastMethodExceptionTest.java
One of the RpcDispatcher tests without exception wrapping had the wrong setting. easy fix.
> wrap exceptions test wrong setting

- src/org/jgroups/fork/ForkChannel.java
- tests/junit-functional/org/jgroups/tests/ForkChannelTest.java
When the ForkChannel constructor is called with create_fork_if_absent as
true a FORK protocol should be created if it does not exist. After
fba4f23282c281873a09256b038f2251829596ba
org.jgroups.protocols.FORK#createForkStack sets the channel from stack
which is never set resulting in an NPE..
channel = new ForkChannel(baseChannel,
"hijack-stack",
"lead-hijacker",
true,
ProtocolStack.ABOVE,
FRAG2.class);
Caused by: java.lang.NullPointerException
at org.jgroups.protocols.FORK.createForkStack(FORK.java:199)
at org.jgroups.fork.ForkChannel.<init>(ForkChannel.java:79)
> Fix regression with ForkChannel

- src/org/jgroups/fork/ForkChannel.java
Whilst it may not be an issue now since there is a sync block on the main channel around getFORK I think it is better to make this thread safe now instead of trying to catch a race condition later.
> Fully initialise FORK protocol before adding it to the stack.

- src/org/jgroups/protocols/TP.java
Backporting [JGRP-1965](https://issues.jboss.org/browse/JGRP-1965) from upstream.
[BZ1275362](https://bugzilla.redhat.com/show_bug.cgi?id=1275362)
> BZ1275362 - Change default thread pool rejection policy to "abort"

- tests/junit-functional/org/jgroups/protocols/GMS_MergeTest.java
Hi Bela, minor fix to a GMS unit test
> Fixed typo when checking views in GMS_MergeTest._testSimpleMerge()

- src/org/jgroups/protocols/GOOGLE_PING.java
Change GOOGLE_PING to use port 443 when creating a connection and no
port is specified in the configuration.
> JGRP-1992 GOOGLE_PING discovery fails if port 443 isn't used

- src/org/jgroups/blocks/MemcachedConnector.java
- src/org/jgroups/demos/StompChat.java
- src/org/jgroups/protocols/ABP.java
- src/org/jgroups/protocols/COUNTER.java
- src/org/jgroups/protocols/DUPL.java
- src/org/jgroups/protocols/Executing.java
- src/org/jgroups/protocols/Locking.java
- src/org/jgroups/protocols/MERGE3.java
- src/org/jgroups/protocols/RELAY.java
- src/org/jgroups/protocols/STOMP.java
- src/org/jgroups/protocols/SWIFT_PING.java
- src/org/jgroups/protocols/tom/StatsCollector.java
- src/org/jgroups/util/SuppressLog.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2786 - Nested "enum"s should not be declared static
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2786
M-Ezzat
> squid:S2786 - Nested enums should not be declared static

- src/org/jgroups/Global.java
- src/org/jgroups/auth/sasl/SecurityActions.java
- src/org/jgroups/blocks/executor/Executions.java
- src/org/jgroups/conf/PropertyConverters.java
- src/org/jgroups/conf/PropertyHelper.java
- src/org/jgroups/demos/KeyStoreGenerator.java
- src/org/jgroups/fork/ForkConfig.java
- src/org/jgroups/jmx/JmxConfigurator.java
- src/org/jgroups/logging/LogFactory.java
- src/org/jgroups/protocols/relay/config/RelayConfig.java
- src/org/jgroups/util/Bits.java
- src/org/jgroups/util/Headers.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
M-Ezzat
> squid:S1118 - Utility classes should not have public constructors

- src/org/jgroups/blocks/ReplicatedHashMap.java
- src/org/jgroups/blocks/ReplicatedTree.java
- src/org/jgroups/protocols/PRIO.java
- src/org/jgroups/protocols/pbcast/FLUSH.java
- src/org/jgroups/protocols/tom/SenderManager.java
- src/org/jgroups/util/Base64.java
- src/org/jgroups/util/ResourceManager.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2974 - Classes without "public" constructors should be "final"
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2974
M-Ezzat
> squid:S2974 - Classes without public constructors should be final

- src/org/jgroups/protocols/FILE_PING.java
characters
Replace File.separatorChar with '/' to fix this issue on Windows
> JGRP-2014 FILE_PING destination file name can include File.separator

- src/org/jgroups/auth/Krb5Token.java
- src/org/jgroups/auth/sasl/FileWatchTask.java
- src/org/jgroups/auth/sasl/SimpleAuthorizingCallbackHandler.java
- src/org/jgroups/demos/ExecutionServiceDemo.java
This pull request is focused on resolving occurrences of Sonar rule squid:HiddenFieldCheck - Local variables should not shadow class fields
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:HiddenFieldCheck
M-Ezzat
> quid:HiddenFieldCheck - Local variables should not shadow class fields

- src/org/jgroups/Message.java
- src/org/jgroups/client/StompConnection.java
- src/org/jgroups/protocols/TCP.java
- src/org/jgroups/protocols/TCP_NIO2.java
- src/org/jgroups/protocols/UNICAST3.java
- src/org/jgroups/protocols/pbcast/StreamingStateTransfer.java
- src/org/jgroups/util/Table.java
- src/org/jgroups/util/Util.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2184 - Math operands should be cast before assignment
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S2184
M-Ezzat
> squid:S2184 - Math operands should be cast before assignment

- tests/junit-functional/org/jgroups/protocols/ENCRYPTAsymmetricTest.java
- fixes failures with IBM JDK
https://issues.jboss.org/browse/JGRP-1993
> JGRP-1993 Compare the encoded keys instead of the SecretKey implementation

- src/org/jgroups/protocols/pbcast/NAKACK2.java
Sometimes buf.add removes messages from the msgs collection,
so it's not ok to cache the size.
> NAKACK2: Fix IndexOutOfBoundsException with trace enabled

- pom.xml
The maven build is broken (mvn install), because https://repository.jboss.org/nexus/service/local/staging/deploy/maven2 cannot be accessed (I don't know why not, haven't found any information about that repo online). JGroups builds fine without it, though.
> Remove unaccessible staging repository

- src/org/jgroups/protocols/COUNTER.java
I was planning to submit a Jira issue with the description for this pull request, but my JBoss Dev account still isn't activated. Anyway, we encountered NullPointerExceptions from the COUNTER protocol in situations where the cluster is split up.
JGroups version: 3.6.10.Final
```
(...)
13:49:29.200 145924 [Incoming-2,matthijs,matthijsws-17469] ERROR org.jgroups.protocols.COUNTER - JGRP000175: failed handling message
java.lang.NullPointerException: null
at org.jgroups.protocols.COUNTER$ReconcileRequest.toString(COUNTER.java:897) ~[jgroups-3.6.10.Final.jar:3.6.10.Final]
at java.lang.String.valueOf(String.java:2994) ~[na:1.8.0_91]
at java.lang.StringBuilder.append(StringBuilder.java:131) ~[na:1.8.0_91]
at org.jgroups.protocols.COUNTER.up(COUNTER.java:181) …
```
> NullPointerException from COUNTER protocol

- src/org/jgroups/protocols/JDBC_PING.java
After updating JGroups the JDBC_PING constantly printed the failed removing row; please delete it manually error message. The cause was my program not exiting cleanly before updating, leaving rows in the cluster table. After the update, the PingData of the previous version failed deserialization and JGroups attempted deleting the offending row. Since the PreparedStatement was created readonly using the default parameters of Connection.prepareStatement(), the call resulted in an error causing the message printout.
The fix creates the statement as updatable so that the row can be deleted.
> fixes JDBC_PING.readAll() executing ResultSet.deleteRow() on readonly ResultSet

- src/org/jgroups/protocols/JDBC_PING.java
Actually the fix turned out to be incomplete as JDBC standard requires for deleteRow() to have all primary keys seleted,. It turned out, this is checked by some drivers such as MySQL.
> select_all_pingdata_sql must select primary keys for ResultSet.deleteRows() to work properly as this required by JDBC standard

- src/org/jgroups/protocols/JDBC_PING.java
Currently JDBC_PING earses the entire JGROUPSPING table when the clear_table_on_view_change option is enabled. This may have unintended side-effects when multiple channels persist ping data. The change alters the delete statement to operate on records of identical cluster_name only so that other clusters are unaffected.
> clearTable() should leave records of other PINGs unaffected

- src/org/jgroups/blocks/locking/LockService.java
Return type of tryLock is boolean while the type of retval is Boolean, so unboxing will be done at returning retval from tryLock. If retval happens to be null, it will throw a null pointer exception. I've added a null check to prevent that.
> Added a null check before returning retval from tryLock.

- src/org/jgroups/protocols/ASYM_ENCRYPT.java
Jira: https://issues.jboss.org/browse/JBEAP-6563
Cherry pick of #327 for EAP 7.1.x and EAP 7.0.x
> [JBEAP-6563] Logs ASYM_ENCRYPT message "key server is currently not set" with debug level

- src/org/jgroups/protocols/ASYM_ENCRYPT.java
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1380657
Cherry pick of #327 for EAP 6.4.z
> [BZ-1380657] Logs ASYM_ENCRYPT message "key server is currently not set" with debug level

- src/org/jgroups/protocols/dns/DefaultDNSResolver.java
https://issues.jboss.org/browse/JGRP-2139
This PR introduces DNS discovery based on [`SRV` entries](https://www.ietf.org/rfc/rfc2782.txt). 
In Kubernetes/OpenShift this allows fine grained discovery (coarse grained is based on Headless Services) upon exposed ports. In order to get this working, one needs to expose a port with a **name** as shows in [this example](https://github.com/slaskawi/jgroups-dns-ping-example/blob/master/service.yaml#L19). An obtained `SRV` entry is used for a standard `A` discovery.
> JGRP-2139 SRV entries parsing for DNS_PING

- src/org/jgroups/protocols/UNICAST2.java
the exception name rather than the entire stack trace is logged
(https://issues.jboss.org/browse/JGRP-1958)
This is a manual backport of
https://github.com/belaban/JGroups/commit/03d7c93145f6a9314c2380f5ad66bdc8ec4209f0
for EAP 6.4 https://bugzilla.redhat.com/show_bug.cgi?id=1399195
@belaban  could you please review if I backported correctly?
> Message delivered up the stack and throwing an exception: a warning with

- src/org/jgroups/protocols/pbcast/NAKACK2.java
Looks like a typo? The actual condition is:
```
if(log.isWarnEnabled() && log_not_found_msgs && !local_addr.equals(xmit_requester) && i > buf.getLow())
log.warn(Util.getMessage("MessageNotFound"), local_addr, original_sender, i);
```
> Fix NAKACK2#log_not_found_msgs description

- src/org/jgroups/client/StompConnection.java
This pull request is specifically aimed at allowing TLS subject validation in the StompConnection https://tools.ietf.org/html/rfc6125#section-2.3
The short version is this:
1) Certificates are encouraged to have either an IP or DNS subject name that can be validated against the host that is serving the certificate, if it matches then the client will trust it, if not then the client may be subject to a man in the middle attack.
2) By default, Java sockets do not perform this validation.  If you google around a bit, you'll find that it is configured via SSLParameters set on each SSLSocket object via the setEndpointIdentificationAlgorithm in the SSLParameters ex:
```
SSLSocket sock = ...;
var sslParameters = sslContext.getDefaultSSLParameters(); …
```
> Allow SSL Sockets to be configured with SSL Parameters

- src/org/jgroups/protocols/TUNNEL.java
https://issues.jboss.org/browse/JGRP-2221
> JGRP-2221 TUNNEL does not close its sock in #destroy()

- src/org/jgroups/logging/CustomLogFactory.java
- src/org/jgroups/logging/JDKLogImpl.java
- src/org/jgroups/logging/Log.java
- src/org/jgroups/logging/Log4J2LogImpl.java
- src/org/jgroups/logging/LogFactory.java
In implementing some log workarounds I found a number of warnings and some argument inconsistencies that I thought should be fixed in the master.
> Fixed some log warnings and argument inconsistencies

- src/org/jgroups/protocols/TP.java
The reaper runnable displayed `logical_addr_cache_expiration` instead of `logical_addr_cache_reaper_interval` as the *interval*
> Fixed reaper runnable toString()

- src/org/jgroups/protocols/BPING.java
When BPING cannot create socket in the configured set of ports, it logs NPE.
```
Caught: java.lang.NullPointerException
java.lang.NullPointerException
at org.jgroups.protocols.BPING.start(BPING.java:76)
at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:861)
at org.jgroups.JChannel.startStack(JChannel.java:993)
at org.jgroups.JChannel._preConnect(JChannel.java:862)
at org.jgroups.JChannel.connect(JChannel.java:366)
at org.jgroups.JChannel.connect(JChannel.java:360)
```
> BPING: error out with meaningful message if socket cannot be created

- src/org/jgroups/protocols/MULTI_PING.java
ns
n.b. tags need to be escaped otherwise you get http://www.jgroups.org/javadoc4/org/jgroups/protocols/MULTI_PING.html
> Fix MULTI_PING JavaDoc

- src/org/jgroups/util/TimeScheduler3.java
Fixes the alike:
```
10:52:48,282 ERROR [org.jgroups.util.TimeScheduler3] (thread-23,ejb,7af0ed52d345) JGRP000169: failed executing taskMERGE3: InfoSender: java.lang.NullPointerException
```
> Minor logging fix in TimeScheduler3

- src/org/jgroups/protocols/INJECT_VIEW.java
Though, to be honest, I am failing to see the usefulness of this protocol. While you can use it for splitting, this cannot be used for merging (which I tried to use this for). If you try to install back the previous merge after split, you are just going to end having to wait for merge to trigger anyway since this is just racy.
2018-05-17 17:01:23,024 INFO  [org.jgroups.protocols.INJECT_VIEW] (default task-1) [INJECT_VIEW] Received request to inject view node-1=node-1/node-2
2018-05-17 17:01:23,028 WARN  [org.jgroups.protocols.pbcast.NAKACK2] (thread-4,null,null) JGRP000011: node-2: dropped message 21 from non-member node-1 (view=[node-2|2] (1) [node-2])
> INJECT_VIEW logging fix: extraneous new lines, duplicate protocol name

- src/org/jgroups/protocols/VERIFY_SUSPECT.java
- tests/other/org/jgroups/tests/InfinispanStackMerge3Test.java
Hi Bela,
here is a manual test for the issue I brought up at last meeting in Milan with MERGE3 when using TCP stack. The test configures Infinispan-like stack, creates partition by installing a view and waits for partition to merge back. This yields results like this one (runs exactly the same setup and only switches TCP/UDP):
```
-------------------------------------------------------------------
Results for TCP
Min merge time=48034
Max merge time=101050
Avg merge time=86958.1
===================================================================
Results for UDP
Min merge time=48019
Max merge time=48104
Avg merge time=48056.0
===================================================================
```
The problem being that merges with fairly low intervals 10-30 seconds can take actually up to 2 …
> Test to demonstrate MERGE3 speed on tcp stack

- src/org/jgroups/blocks/cs/NioConnection.java
- src/org/jgroups/blocks/cs/TcpConnection.java
The memory leak described in https://issues.jboss.org/browse/JGRP-1530 may still occur if the bind IP address passed to the client socket is null and the resulting source and destination addresses are equal. This is because the local IP address of the client socket after binding and before connecting to the remote server is 0.0.0.0 and it differs from the destination IP address. After connecting the local IP address is being updated to the actual value.
> Fix memory leak

- src/org/jgroups/protocols/dns/DefaultDNSResolver.java
This PR fixes JGRP-2296:
```
2018-10-05 20:08:38,083 DEBUG [org.jgroups.protocols.dns.DNS_PING] (thread-14,ejb,98670c2eeed5) Performing initial discovery
2018-10-05 20:08:38,086 DEBUG [org.jgroups.protocols.dns.DNS_PING] (thread-14,ejb,98670c2eeed5) Entries collected from DNS: [10.42.3.44:7600, 10.42.3.56:7600]
2018-10-05 20:08:38,087 DEBUG [org.jgroups.protocols.dns.DNS_PING] (thread-14,ejb,98670c2eeed5) Performing discovery of the following hosts [10.42.3.56:7600, 10.42.3.44:7600, e8c677a1d275, 98670c2eeed5]
2018-10-05 20:08:38,088 DEBUG [org.jgroups.protocols.dns.DNS_PING] (thread-14,ejb,98670c2eeed5) 98670c2eeed5: sending discovery request to 10.42.3.56:7600
2018-10-05 20:08:38,088 DEBUG [org.jgroups.protocols.dns.DNS_PING] (thread-14,ejb,98670c2eeed5) 98670c2eeed5: sending discovery …
```
> JGRP-2296: Preserve port number from SRV records

- src/org/jgroups/client/StompConnection.java
When running is false this error may be expected
Note: I saw this error logging behavior in `3.6.9.Final` not sure if this is the correct branch to merge into to fix both 3.x and 4.x, nor am I sure what the differences are.
> JGRP-2306 only log error for unexpected disconnects

- src/org/jgroups/protocols/VERIFY_SUSPECT.java
This is regarding point #2 raised here: https://issues.jboss.org/browse/JGRP-2287
The timer field is used as a flag to exit the thread's while loop but this field's visibility isn't guaranteed. The field should be volatile.
Point #1 seems to be OK to me, as all those methods use locks internally, and the loop should behave as expected.
> The timer field is used as a flag to exit the thread's while loop

- src/org/jgroups/protocols/VERIFY_SUSPECT.java
We should use System.nanoTime() instead of System.currentTimeMillis(). This is because System.currentTimeMillis() uses the underlying operating system clock, which may change and cause unexpected behaviour. System.nanoTime() on the other hand uses JVM's time source, which doesn't change throughout its lifetime.
Example in case of System.currentTimeMillis():
1. The suspects are added to the queue.
2. The timer thread starts.
3. Just before suspects.poll() method call the system clock gets updated a few seconds forward due to ntp.
4. Suspects are all drained as expired, unexpectedly.
> Use System.nanoTime() instead of System.currentTimeMillis().

- src/org/jgroups/blocks/cs/NioConnection.java
https://issues.jboss.org/browse/JGRP-2328
I only made the minimal change: I left the Reader in state `reading`, just like if the stop request arrived during `register(SelectionKey.OP_READ)`. I can try to clean it up and ensure it always gets in state `done` if you want.
> JGRP-2328 NioConnection.Reader thread can miss stop request

- pom.xml
I noticed this mistake in the POM as every build would attempt to go and check if there were new snapshots to be fetched from the release repository.
This should speed up the build so to not waste time with that.
> Don't attempt to download SNAPSHOTS from the JBoss Release repository

- src/org/jgroups/blocks/cs/NioConnection.java
- src/org/jgroups/nio/Buffers.java
https://issues.jboss.org/browse/JGRP-2355
This allows TCP_NIO2 to work under JDK8 when build using JDK9 or above.  Verified using JDK11.
> JGRP-2355 Fix JDK8 compatibility with ByteBuffer methods.

- src/org/jgroups/util/PropertiesToAsciidoc.java
- src/org/jgroups/util/Util.java
- tests/junit-functional/org/jgroups/tests/UtilTest.java
- `replaceProperties` is deprecated. All code reference in Jgroups were removed.
- `substituteVariable` support `Properties` to avoid pollute System#properties
- The comment https://github.com/belaban/JGroups/pull/439/files#diff-3b288edf7316f3ebf2df3389cfe89482R193 was not reflecting the test case. I updated the test suite and fix with https://github.com/belaban/JGroups/pull/439/files#diff-4291e17fb095e78fe48681c905a41204R4399
> JGRP-2378 Util replaceProperties fails when the input start with $

- src/org/jgroups/protocols/ASYM_ENCRYPT.java
- src/org/jgroups/protocols/DH_KEY_EXCHANGE.java
- src/org/jgroups/protocols/Encrypt.java
- src/org/jgroups/protocols/EncryptHeader.java
- src/org/jgroups/protocols/SSL_KEY_EXCHANGE.java
- src/org/jgroups/protocols/SYM_ENCRYPT.java
- tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_LeaveTest.java
- tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_LeaveTestCbc.java
- tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_LeaveTestKeyExchangeCbc.java
- tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_Test.java
- tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_TestCbc.java
- tests/junit-functional/org/jgroups/protocols/ASYM_ENCRYPT_TestKeyExchangeCbc.java
- tests/junit-functional/org/jgroups/protocols/ENCRYPTKeystoreTest.java
- tests/junit-functional/org/jgroups/protocols/ENCRYPTKeystoreTestCbc.java
- tests/junit-functional/org/jgroups/protocols/EncryptTest.java
- tests/junit-functional/org/jgroups/protocols/SYM_ENCRYPT_Test.java
- tests/junit-functional/org/jgroups/protocols/SYM_ENCRYPT_TestCbc.java
- tests/junit-functional/org/jgroups/tests/SizeTest.java
This change allows JGroups to support symmetric encryption algorithms that require an initialization vector (IV). An important example is "AES/CBC/PKCS5Padding" which uses the CBC cipher mode. 
The main changes that were required are as follows:
- Added a sym_iv_length field to Encrypt. This must be set to a non-zero value when using a cipher mode that requires an IV.
- Added an iv field to the EncryptHeader (which may be null if the cipher mode does not require an IV).
- Since the IV is passed when the Cipher is initialized and the IV is created per-message, cipher initialization is now deferred until the message is being encrypted/decrypted.
- Since the key is passed to the Cipher.init() method and init() is deferred, we now store the Key rather than the Cipher in the key_map field of …
> Adding IV support to SYM_ENCRYPT and ASYM_ENCRYPT protocols (JGRP-2386).

- src/org/jgroups/JChannel.java
This reintroduces the `org.jgroups.JChannel#JChannel(java.net.URL)` to ease library usage.
Infinispan 9.4.x (9.4.19) uses a URL to load the JGroups configuration from the infinispan configuration.
When an external jgroups stack configuration file is used:
See: "Using an external JGroups file" in https://infinispan.org/docs/9.4.x/user_guide/user_guide.html#using_an_external_jgroups_file
When creating the JGroups stack, infinispan uses the constructor in org.jgroups.JChannel#JChannel(...) which takes a URL as parameter.
See: https://github.com/infinispan/infinispan/blob/9.4.x/core/src/main/java/org/infinispan/remoting/transport/jgroups/JGroupsTransport.java#L586
However this constructor is only present in versions up-to including 4.0.22 …
> JGRP-2477 Reintroduce support for configuring a JChannel via URL

- src/org/jgroups/protocols/FD.java
The FD Monitor was split into a heartbeat sender task and a timeout check task, similar to FD_ALL and FD_ALL2. This prevents the timeout check in the FD protocol from being block by the transport.
Ticket: https://issues.redhat.com/browse/JGRP-2486.
> JGRP-2486 FD Monitor gets stuck on TransferQueueBundler

- src/org/jgroups/protocols/SSL_KEY_EXCHANGE.java
- src/org/jgroups/util/SSLContextFactory.java
https://issues.redhat.com/browse/JGRP-2484
This fixes the ASYM_ENCRYPT_TestKeyExchange failures.
> JGRP-2484 SSL_KEY_EXCHANGE Add keystore as truststore

- src/org/jgroups/protocols/dns/DNS_PING.java
- tests/junit-functional/org/jgroups/protocols/dns/DNS_PINGTest.java
https://issues.redhat.com/browse/JGRP-2505
In multi-region deployments, it'd be useful to combine addresses from multiple DNS queries to form the cluster. This simple change makes the "dns_query" parameter to DNS_PING a comma-separated list of queries as opposed to a single query like it is currently.
> JGRP-2505: change dns_query to support a comma-separated list of queries

- src/org/jgroups/protocols/dns/DNS_PING.java
- tests/junit-functional/org/jgroups/protocols/dns/DNS_PINGTest.java
It turns out that our application team is still on JGroups 4.x and not updating to 5.x for the next release. Would you be willing to roll this into the next 4.x release? Would really appreciate it! Thanks :)
In multi-region deployments, it'd be useful to combine addresses from multiple DNS queries to form the cluster. This simple change makes the "dns_query" parameter to DNS_PING a comma-separated list of queries as opposed to a single query like it is currently.
> JGRP-2505: (4.x) change dns_query to support a comma-separated list of queries

- src/org/jgroups/protocols/TP.java
Upport of #515 for 5.x
#515 contains a detailed description of the bugfix for 4.0.x
> [5.x] Added missing destination check before processing message batch

- src/org/jgroups/protocols/TP.java
We found a bug with message batching on the receiver side.
The bug leads to the new node silently ignoring messages from other nodes so it can not completely join the cluster.
Steps to reproduce:
1. Form a cluster of 2 nodes
node 1 has physical address ip1 and logical address A
node 2 has physical address ip2 and logical address B
2. Shutdown B
3. A still sends unicast messages to B (for example responses that B did not wait for).
These messages are not acknowledged and so UNICAST3 keeps them in its send table.
The messages are also retransmitted in an interval.
4. Start C on the same physical address ip2 as B while messages are still sent/retransmitted from A to B.
5. The messages to B will arrive at C.
`TP.handleSingleMessage` filters out single messages to the old destination B before …
> [4.0.x] Added missing destination check before processing message batch

- src/org/jgroups/protocols/TP.java
Upport of #515 for 4.1.x
#515 contains a detailed description of the bugfix for 4.0.x
> [4.1.x] Added missing destination check before processing message batch

- src/org/jgroups/protocols/TP.java
Upport of #515 for 4.2.x
#515 contains a detailed description of the bugfix for 4.0.x
> [4.2.x] Added missing destination check before processing message batch

- doc/manual/protocols.adoc
A couple things in encryption docs I found slightly misleading.
- SYM_ENCRYPT and ASYM_ENCRYPT need to go above NAKACK2.
- You can use other keystore formats with SYM_ENCRYPT with the keystore_type config attribute.
> Clarify keystore type with SYM_ENCRYPT

- ivy.xml
- pom.xml
- src/org/jgroups/blocks/cs/TcpConnection.java
- src/org/jgroups/blocks/cs/TcpServer.java
- src/org/jgroups/protocols/SSL_KEY_EXCHANGE.java
- src/org/jgroups/protocols/TUNNEL.java
- src/org/jgroups/stack/GossipRouter.java
- src/org/jgroups/stack/RouterStub.java
- src/org/jgroups/stack/RouterStubManager.java
- src/org/jgroups/util/DefaultSocketFactory.java
- src/org/jgroups/util/SocketFactory.java
- src/org/jgroups/util/SslContextFactory.java
- src/org/jgroups/util/Util.java
- tests/junit-functional/org/jgroups/protocols/TLSTest.java
- tests/other/org/jgroups/tests/RouterStubGet.java
https://issues.redhat.com/browse/JGRP-2487
This contains some fixes to make SocketFactories that return SSL sockets work in TCP (UDP and TCP_NIO are not supported).
Additionally the GossipRouter CLI has been enhanced to allow SSL configuration, including the ability to set SNI names.
@pruivo can you please add your review.
Once approved, I'll create a forward port for 5.x
> [4.x] JGRP-2487 TLS Transport

- src/org/jgroups/protocols/relay/RELAY2.java
- tests/junit-functional/org/jgroups/tests/Relay2Test.java
SiteMaster was sent back to the originator a message with
SITE_UNREACHABLE but it sets a SiteUUID as destination Address. The
originator discards because it cannot handle this type of Address.
https://issues.redhat.com/browse/JGRP-2570
> [4.x] JGRP-2570 SITE_UNREACHABLE is discarded on originator

- src/org/jgroups/protocols/relay/RELAY2.java
- tests/junit-functional/org/jgroups/tests/Relay2Test.java
SiteMaster was sent back to the originator a message with
SITE_UNREACHABLE but it sets a SiteUUID as destination Address. The
originator discards because it cannot handle this type of Address.
https://issues.redhat.com/browse/JGRP-2570
> JGRP-2570 SITE_UNREACHABLE is discarded on originator

- src/org/jgroups/protocols/TP.java
sendMulticast is no longer part of the TP class as of https://github.com/belaban/JGroups/commit/e290a38b5eac738b7cdbb2076e2f637d7b5a660f
> Remove reference to sendMulticast from comments

- .github/workflows/ci.yml
- .travis.yml
This GH action will verify compilation using JDK 11 across platforms on master branch and pull requests submitted against it. This will prevent issues like merging uncompilable code, merge conflicts, unresolvable artefacts, etc.
Commits / PRs that have been tested will be rendered on the UI with a green tick next to it. Note that this does not enforce anything (but it is possible to e.g. require passing checks in repo settings if desired).
Going forward, the appropriate tests should be executed, however, they don't seem to be in a runnable state at the moment when executed form maven; also will likely need to account for the environment (e.g. multicast, timing issues).
Here's an example run - https://github.com/rhusar/JGroups/actions/runs/1414565300 - the PR needs to be merged for the CI …
> [master] Introduce continuous integration testing using GitHub Actions

- src/org/jgroups/blocks/cs/NioBaseServer.java
This change addresses a case that wasn't covered by the original fix for [JGRP-2531](https://issues.redhat.com/browse/JGRP-2531). Specifically, we have found that in certain cases, the `finishConnect()` can return false, even though `isConnectable()` returned true. In these cases, if the code proceeds to call `conn.receive()`, the `NotYetConnectedException` is thrown, which results in a WARN-level log message.
The fix is, when `isConnectable()` or `isAcceptable()` returns true, the code no longer falls through and checks the `isReadable()` or `isWritable()` flags.
> JGRP-2531 Handle case where finishConnect() returns false even though isConnectable() returned true.

- src/org/jgroups/protocols/dns/AddressedDNSResolver.java
- src/org/jgroups/protocols/dns/DefaultDNSResolver.java
I'm trying to use JGroups with HashiCorp Consul as the DNS engine during service discovery. Now this is impossible, because the Consul resolves the addresses of services in its own namespace (for example, `7f000801.addr.dc1.consul.`) which must be resolved again through `DnsContext`. This PR will fix it.
> fix use case DNSResolver for Consul

- src/org/jgroups/stack/DiagnosticsHandler.java
@belaban IIUC `diag.enabled` is the replacement property for `enable_diagnostics` in which case this updates the descriptions accordingly.
> Update enable_diagnostics to diag.enabled in property descriptions

- src/org/jgroups/util/ThreadPool.java
JGroups generate thread dump in the same log of the server. When dealing with suspected nodes, the logs become big and it is hard to find out the root cause.
This PR allows the developer to set a custom path to generate the thread dump.
> Support to generate thread dump in a file

- .github/dependabot.yml
Cleanup for hard-coded dependencies - which should be rather ignored by talking to dependabot on the PRs rather than hard coded here (e.g. there is no reason why not to upgrade the compiler plugin) and a fix for https://github.com/belaban/JGroups/commit/74e293af1bd867a95bad8e3d4630df9a984668ed which I merged at a wrong indent level (gotta love yml!).
This yields an error that you can view at https://github.com/belaban/JGroups/network/updates where you can trigger dependabot manually.
> Fix and cleanup dependabot.yml

- tests/other/org/jgroups/tests/ParseMessages.java
- tests/other/org/jgroups/tests/ParsePacketDissections.java
For a test that has a massive amount of data, like 100GB, I believe the fast way to parse JGroups messages is using `ParsePacketDissections`.
This PR moves the instance creation in `ParseMessages::main` to an inner class `InnerParseMessages`
I can reuse `InnerParseMessages` to print `JGroups` messages from other classes.
> Parse Packet Dissection

- conf/auth_X509.xml
- conf/auth_krb5.xml
- conf/auth_regex.xml
- src/org/jgroups/protocols/AUTH.java
- Move the initialization of the X509Token to AUTH.start() method instead of AUTH.init() method since the certificate properties are not defined yet when the init() method is called;
- Adjust the sample AUTH configurations to include the auth_token. prefix;
> JGRP-2626 Fix X509Token Initialization

- build.xml
- mr/19/src/org/jgroups/util/jdkspecific/ThreadCreator.java
- pom.xml
- src/org/jgroups/util/DefaultThreadFactory.java
- src/org/jgroups/util/ThreadPool.java
- src/org/jgroups/util/Util.java
- src/org/jgroups/util/jdkspecific/ThreadCreator.java
https://issues.redhat.com/browse/JGRP-2631
> JGRP-2631 Multi-Release JAR

- src/org/jgroups/protocols/FD_SOCK2.java
- tests/junit-functional/org/jgroups/protocols/FD_SOCK2_Test.java
Adds test for [JGRP-2647](https://issues.redhat.com/browse/JGRP-2647). Exposes setters/getters. ~~Includes https://github.com/belaban/JGroups/pull/670.~~
> Test case for JGRP-2647.

- src/org/jgroups/protocols/pbcast/GMS.java
It appears that this was only supposed to log when log_collect_msgs is true, but an accidental semicolon resulted in the log statement always running.
> Remove semicolon from if statement

- src/org/jgroups/util/TLS.java
TLS 1.2 is fairly old and better alternatives are available. It seems better to rely on the defaults of oracle than to to manually downgrade settings.
> do not default to very old protocols, let the jvm pick a secure value

- src/org/jgroups/protocols/relay/Relayer.java
Some logs messages use `relay.getAddress()` and others `channel.getAddress()`. I'm not sure if I chose the correct one.
> Fix trace format in Relayer class

- src/org/jgroups/protocols/relay/Relayer.java
JIRA: https://issues.redhat.com/browse/JGRP-2711
It fixes most of the tests in Infinispan test suite. I still have a hand full of failures to look at.
> JGRP-2711 Relayer#getSiteNames isn't returning all the sites available

- src/org/jgroups/blocks/Cache.java
- src/org/jgroups/blocks/GridFile.java
- src/org/jgroups/protocols/FD_HOST.java
- src/org/jgroups/protocols/FD_SOCK.java
- src/org/jgroups/protocols/FD_SOCK2.java
- src/org/jgroups/protocols/FailureDetection.java
- src/org/jgroups/protocols/SOS.java
- src/org/jgroups/protocols/pbcast/GMS.java
- src/org/jgroups/protocols/pbcast/ViewHandler.java
- src/org/jgroups/stack/GossipRouter.java
- src/org/jgroups/util/Util.java
https://issues.redhat.com/browse/JGRP-2736
> JGRP-2736 Use Instant instead of Date

- .github/workflows/ci.yml
Well, it has been GA for a while now, but the `temurin` build just wasn't available to us here. Ready to go now.
> CI: JDK 21 is now GA.

- tests/junit-functional/org/jgroups/tests/MessageCacheTest.java
Fixes regression caused by backport - https://github.com/belaban/JGroups/commit/5d7290d20861936c8a2f939d0870acdbb22f6a35
The `ObjectMessage` was introduced in 5.0 :-)
> [4.x] Fix MessageCacheTest compilation for JGRP-2747.

- src/org/jgroups/util/Util.java
`CACHED_ADDRESSES` is been overwritten all the time the method is invoked when `filter!=null`. This PR fixes it (assuming it wasn't intentional)
> JGRP-2739 Cache addresses on first access

- src/org/jgroups/protocols/Discovery.java
A [recent commit](https://github.com/belaban/JGroups/commit/40a615e45c0550d5f91b4fd8c01a3b4950d9e5be) in 5.3.2 broke the binary compatibility with modules like JGroups K8S. It's no longer possible to use JGroups K8S 2.0.1 with JGroups 5.3.2:
```java
Caused by: java.lang.NoSuchMethodError: 'org.jgroups.util.ByteArray org.jgroups.protocols.kubernetes.KUBE_PING.marshal(org.jgroups.protocols.PingData)'
at org.jgroups.protocols.kubernetes.KUBE_PING.findMembers(KUBE_PING.java:278)
at org.jgroups.protocols.Discovery.callFindMembersInAllDiscoveryProtocols(Discovery.java:393)
at org.jgroups.protocols.Discovery.findMembers(Discovery.java:240)
at org.jgroups.protocols.Discovery.down(Discovery.java:430)
at org.jgroups.protocols.MERGE3.down(MERGE3.java:268)
at …
```
> Add single-argument method version for binary compatibility

- src/org/jgroups/NioMessage.java
This fixes ReadOnlyBufferException when sending a NioMessage with a read-only ByteBuffer.
> JGRP-2777 ReadOnlyBufferException in NioMessage

- src/org/jgroups/Global.java
- src/org/jgroups/Version.java
- tests/junit-functional/org/jgroups/tests/VersionTest.java
https://issues.redhat.com/browse/JGRP-2782
Some whitespace was changed too, sorry. Didn't know how to stop my IDE form doing this.
> JGRP-2782 - TP: new global config VERSION_CHECK_MICRO should consider Jgroups as incompatible if Micro Version differs

- build.xml
- pom.xml
- src/module-info.java
Adds an explicit module-info to the final artifact
> Add explicit module info

- src/org/jgroups/auth/RegexMembership.java
I checked other types of tokens and it seems to be the only one performing param checks in init() stage or before.
However I didn't have time to write tests for it, sorry.
> DISCUSSION-799 delay param checks from init() to start() in RegexMembership

- src/org/jgroups/stack/GossipRouter.java
https://issues.redhat.com/browse/JGRP-2805
> JGRP-2805 GossipRouter NPE on startup

- src/org/jgroups/util/TLS.java
This change allows setting TLS SSLContext directly when wanting to configure the SSLContext programmatically
> JGRP-2809 Allow setting TLS SSLContext programmatically

- src/org/jgroups/protocols/SimplifiedTransferQueueBundler.java
- src/org/jgroups/protocols/TransferQueueBundler.java
Because it doesn't work as it's overwritten in start
> JGRP-2810 Disallow setting queue in TransferQueueBundler constructor

- src/org/jgroups/protocols/Bundler.java
- src/org/jgroups/protocols/PerDestinationBundler.java
- src/org/jgroups/protocols/RemoveQueueBundler.java
- src/org/jgroups/protocols/RingBufferBundler.java
- src/org/jgroups/protocols/RingBufferBundlerLockless.java
- src/org/jgroups/protocols/RingBufferBundlerLockless2.java
- src/org/jgroups/protocols/TP.java
- src/org/jgroups/protocols/TransferQueueBundler.java
- src/org/jgroups/protocols/TransferQueueBundler2.java
This makes TP rename all bundler threads (previously only done for TransferQueueBundler+RingBufferBundler) and also makes TP not care about the specific bundler type being used
> JGRP-2808 Make TP rename all bundler threads

- src/org/jgroups/util/Util.java
[asIterator](https://developer.android.com/reference/java/util/Enumeration#asIterator()) was introduced in android API 33. This restricts usage on older devices. 
This change was introduced in 5.3.2. There are network detection issues that existed in 5.3.1 but that were resolved between 5.3.2 and 5.3.9. 
Same as other pull request only targeting master
> Refactor use of asIterator() to reduce required android SDK on master

- src/org/jgroups/protocols/Discovery.java
We are getting this exception in runtime when application starts and discovery is scheduled.
```
Exception in thread "jgroups-6,aaaaaaaaaaaa-1111" java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "data" is null
at org.jgroups.protocols.Discovery.handle(Discovery.java:364)
at org.jgroups.protocols.Discovery.up(Discovery.java:299)
at org.jgroups.protocols.TP.passMessageUp(TP.java:1188)
at org.jgroups.util.SubmitToThreadPool$SingleLoopbackHandler.run(SubmitToThreadPool.java:77)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
```
Reason for that might be a regression after refactoring: null-check for …
> Fix NPE when data is null in Discovery

- src/org/jgroups/protocols/FD_SOCK2.java
For some reason this always bothers me :)
> Fix FD_SOCK2 startup log to show *:port instead of *.port

- src/org/jgroups/protocols/dns/DNS_PING.java
My setup is a set of Keycloak 18.0.2 clusters in an environment with nomad and consul. We're using DNS_PING with SRV records for a long time now and the JGroups setup is pretty simple:
```
JGROUPS_DISCOVERY_PROTOCOL=dns.DNS_PING
JGROUPS_DISCOVERY_PROPERTIES="dns_query="${dns_query}",dns_record_type="SRV""
JGROUPS_TRANSPORT_STACK="tcp"
```
When migrating this to Keycloak 23.0.7, I found that the dns_record_type separated with a comma is not supported anymore. With the documentation I found on the internet and discussions and issue in the JGroups, Infinispan, Keycloak github projects, I failed to get SRV records running with something straight-forward like this:
```
<infinispan ...>
<jgroups>
<stack name="dns-ping">
<dns.DNS_PING dns_record_type="SRV"
dns_query="${dns_query}"/>
<TCP …
```
> allow to configure dns_record_type with a system property

- src/org/jgroups/blocks/cs/BaseServer.java
```
2024-10-01 11:42:50.266+0000 [TQ-Bundler-7,app,app-5b57dcfd44-2n7wf-59692] TRACE org.jgroups.protocols.TCP [] [] - [trace] 10.244.8.175:7800: failed connecting to 10.244.15.77:7800: java.net.SocketTimeoutException: Connect timed out
2024-10-01 11:42:50.266+0000 [TQ-Bundler-7,app,app-5b57dcfd44-2n7wf-59692] TRACE org.jgroups.protocols.TCP [] [] - [trace] 10.244.8.175:7800: removed connection to 10.244.15.77:7800
2024-10-01 11:42:50.348+0000 [TQ-Bundler-7,app,app-5b57dcfd44-2n7wf-59692] TRACE org.jgroups.protocols.TCP [] [] - [trace] 10.244.8.175:7800: connecting to 10.244.15.77:7800
2024-10-01 11:42:52.351+0000 [TQ-Bundler-7,app,app-5b57dcfd44-2n7wf-59692] TRACE org.jgroups.protocols.TCP [] [] - [trace] 10.244.8.175:7800: failed connecting to 10.244.15.77:7800: …
```
> JGRP-2838 Fix infinite loop in TCP when using use_acks

- src/org/jgroups/util/Util.java
When used on android mobile devices the standard java.net, network interfaces and address classes does not match the state of the Connectivity manager. for example when connectivity manager make a call back saying that an ip is available, Util.checkIfValidAddress(it,"") will throw an exception saying it is not valid. This is the case even if Util.resetCacheAddresses(true,true) is called first
Adding this method allow for the connectivity manager to make a call back like the following:
```kotlin
val networkCallback =  object : NetworkCallback() {
override fun onLinkPropertiesChanged(network: Network, linkProperties: LinkProperties) {
linkProperties.linkAddresses.forEach {
Log.d(TAG, "Link Address: ${it.address}")
// This in theory, should be called when the network changes and should …
```
> add set cache method in Util

- src/org/jgroups/protocols/NAKACK4.java
- src/org/jgroups/protocols/ReliableUnicast.java
- src/org/jgroups/protocols/UNICAST3.java
- src/org/jgroups/util/AckTable.java
This change adds a getNumUnackedMessages(dest) method to UNICAST3/4//NAKACK4 which can be used for e.g. metrics.
> Methods for unacked messages metrics

- src/org/jgroups/util/Util.java
https://issues.redhat.com/browse/JGRP-2868
@belaban We need this for 5.4.x and 5.3.x
> JGRP-2868 Util#loadClass throw NPE when getContextClassLoader is null

- src/org/jgroups/protocols/pbcast/GMS.java
Not all GMS messages have DONT_BLOCK flag today. This means that they can be blocked in UNICAST4/NAKACK4.
> Add DONT_BLOCK to all GMS messages

- src/org/jgroups/protocols/ReliableMulticast.java
- src/org/jgroups/protocols/ReliableUnicast.java
The lock needs be taken before incrementing seqno
> Fix send_atomically lock in ReliableUni/Multicast

- src/org/jgroups/blocks/cs/NioConnection.java
- src/org/jgroups/blocks/cs/TcpConnection.java
Problem: I'm using TCP_NIO2 and seeing sporadic cookie warning messages but cannot identify where the connections are from since peer information is not logged.
This change tweaks the logging of cookie warning message in NioConnection to contain peer information and be consistent with TcpConnection.
> Consistent tcp/nio cookie warning messages
